### PR TITLE
feat(telegram): add support for message_thread_id

### LINKED ISSUE #361: Support for Telegram thread ID
The `sendMessage` method (https://core.telegram.org/bots/api#sendmessage) now supports an optional `message_thread_id` to send the message to a super group topic. It would be great if this can be supported by shoutrrr.

My preferred way to support it is to specify the chat id of the super group in the format of:

```
telegram://$token@telegram?chats=$chat_id:$message_thread_id,$chat_id2,$chat_id3:$message_thread_id
```

### PR DESCRIPTION
**Pull request by yegle**
Reference: https://core.telegram.org/bots/api#sendmessage

closes #361

### CODE REVIEW

**Comment by piksel** [comment]
Looks good, but there are no tests. Also, how do you retrieve the thread ID?

**Comment by yegle** [comment]
Test added, info on how to obtain the message_thread_id added.

**Review by piksel — APPROVED** [review]
Great work! I'm not sure how I feel about linking a SO question in the docs, but perhaps it's better than nothing. We could always update the docs at a later time.

**Comment by yegle** [comment]
Is it okay to keep the `$chat_id:$message_thread_id` format? I only proposed it because it's easy to implement, but we can change to something more formal.

**Comment by piksel** [comment]
Yeah, I think it's a good way to do it. Normally I would prefer to add another parameter, but since this is directly relating to a target it makes sense to use this. It also doesn't need to be escaped which is a plus!

**Comment by instantdreams** [comment]
Documentation needs to be updated to reflect use and examples of Topic ID

**Pull request merged**
