### PR TITLE
feat(services): add hangouts chat service

### PR DESCRIPTION
**Pull request by arnested**
Send notifications as simple messages to an incoming webhook in Hangouts Chat.

### CODE REVIEW

**Comment by simskij** [comment]
Would you mind moving the documentation to the overview.md file? Other than that, I think it's good to go. 👍

**Comment by arnested** [comment]
@simskij, I moved the documentation to `overview.md` -- the explanaition on how to construct the URL should probably move into its own documentation page. I can do that later today or tomorrow. Either in this PR or a new one.

**Comment by arnested** [comment]
@simskij, separate documentation page added. I think it is ready now.

**Comment by simskij** [comment]
Thank you kindly for the contribution! 🙏🏼

**Comment by simskij** [comment]
@all-contributors add @arnested for code

**Pull request merged**
