### PR TITLE
Move CLI command to /shoutrrr

### PR DESCRIPTION
**Pull request by arnested**
This will make the CLI command installable by running:

```
go install github.com/containrrr/shoutrrr/shoutrrr@latest
```

When installing using `go install` previously the command got installed
with the binary name `cli`.

### CODE REVIEW

**Review by simskij — APPROVED** [review]

**Comment by piksel** [comment]
I would probably prefer it to be shoutrrr/shoutrrr instead. I feel like the extra "cmd" doesn't serve any purpose and is less often used as a pattern for CLIs (in my experience).

**Comment by simskij** [comment]
> I would probably prefer it to be shoutrrr/shoutrrr instead. I feel like the extra "cmd" doesn't serve any purpose and is less often used as a pattern for CLIs (in my experience).

It is a common convention for go applications, however.

**Comment by arnested** [comment]
> I would probably prefer it to be shoutrrr/shoutrrr instead. I feel like the extra "cmd" doesn't serve any purpose and is less often used as a pattern for CLIs (in my experience).

I would also say it's quite common. A few examples:

* github.com/go-delve/delve/cmd/dlv
* github.com/fzipp/gocyclo/cmd/gocyclo
* github.com/golangci/golangci-lint/cmd/golangci-lint
* golang.org/x/exp/cmd/gorelease
* golang.org/x/tools/cmd/stringer
* golang.org/x/tools/cmd/goimports

**Comment by piksel** [comment]
Yeah, but those either have multiple binaries (or plan to?), and then it makes sense, but for a single-binary project like this (which instead uses sub-commands), I prefer the style of:
- github.com/onsi/ginkgo/ginkgo
- github.com/spf13/cobra/cobra
- github.com/axw/gocov/gocov
- github.com/davecgh/go-spew/spew

**Comment by simskij** [comment]
You battle it out 😂 I'm down with whichever, although I have a slight preference for the `./cmd` pattern.

**Comment by arnested** [comment]
I'll change it. The most important part for me was just being able to `go install` with the right binary name. I also have preference for `cmd` and think it also communicates the intention clearing when browsing the files and directories. But I can live with both.

**Comment by arnested** [comment]
Change pushed. I'll squash the two commits before this is final and ready to merge.

Putting the command in the folder named `./shoutrrr` required small changes to the build script and Dockerfile because the previous build script produced the cli command binary in the root folder under that name.

**Comment by piksel** [comment]
Haha, sorry for being unreasonable :D I don't care that much either. I'm just selfishly plotting to reduce the huge amount of characters I have to type :D

**Review by piksel — APPROVED** [review]

**Comment by arnested** [comment]
I have squashed the commits, and it's ready for merge.

**Comment by arnested** [comment]
@piksel or @simskij, would you merge it?

**Pull request merged**
